#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

project_path="$( cd "$( dirname "$0" )/.." && pwd )"
jsdoc2md="${project_path}/node_modules/.bin/jsdoc2md"

if [ ! -x "${jsdoc2md}" ]; then
    echo "could not find jsdoc2md locally, try npm install jsdoc-to-markdown"
    exit 99
fi

"$project_path/node_modules/.bin/jsdoc2md" "$project_path/src/index.js" --template "$project_path/doc/README.md.hbs" > "$project_path/README.md"
